namespace Formbase.M3L;

/// <summary>
/// Which axis of the declaration vocabulary a dropped M3L construct demands. The kinds mirror the
/// four evidences of the flat-vocabulary issue plus the constraint surface: Formology mapping
/// rules 3/4 (relations), rule 5 (time binding), the identity/display split, derived fields that
/// ride on relations, declared value constraints, and constructs the spike deliberately leaves
/// unresolved.
/// </summary>
public enum VocabularyGapKind
{
    /// <summary>A foreign-key style reference to another entity (Formology rule 4 — true now).</summary>
    Relation,

    /// <summary>Hard/soft binding mode on a reference (Formology rule 5 — fixed then vs true now).</summary>
    TimeBinding,

    /// <summary>A display label distinct from the extraction name (identity/display split).</summary>
    IdentityDisplay,

    /// <summary>A lookup/rollup/computed field — derived over a relation, not stored raw.</summary>
    Derived,

    /// <summary>A declared value constraint (enum membership, range, uniqueness) with no hint slot.</summary>
    Constraint,

    /// <summary>A construct the spike does not attempt to resolve (inheritance, views, imports).</summary>
    Unresolved,
}

/// <summary>
/// One M3L construct the flat <c>FieldHint</c> vocabulary cannot carry — measured demand for the
/// richer declaration vocabulary, generated by code rather than asserted by prose.
/// </summary>
public sealed record VocabularyGap(
    string Model,
    string? Field,
    VocabularyGapKind Kind,
    string Construct,
    string Detail);
